apiVersion: apps/v1
kind: Deployment
metadata:
  name: wininbrowser-int
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wininbrowser-int
  template:
    metadata:
      labels:
        app: wininbrowser-int
    spec:
      containers:
        - name: wininbrowser-int
          image: judelgadoc/wininbrowser_int
          ports:
            - containerPort: 55694
            - containerPort: 29162
---
apiVersion: v1
kind: Service
metadata:
  name: wininbrowser-int
spec:
  selector:
    app: wininbrowser-int
  ports:
    - protocol: TCP
      port: 55694
      targetPort: 55694
    - protocol: TCP
      port: 29162
      targetPort: 29162
