apiVersion: apps/v1
kind: Deployment
metadata:
  name: wininbrowser-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wininbrowser-mq
  template:
    metadata:
      labels:
        app: wininbrowser-mq
    spec:
      containers:
        - name: wininbrowser-mq
          image: rabbitmq:3-alpine
          ports:
            - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: wininbrowser-mq
spec:
  selector:
    app: wininbrowser-mq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672

