apiVersion: apps/v1
kind: Deployment
metadata:
  name: wininbrowser-wa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wininbrowser-wa
  template:
    metadata:
      labels:
        app: wininbrowser-wa
    spec:
      containers:
        - name: wininbrowser-wa
          image: judelgadoc/wininbrowser_wa
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wininbrowser-wa
spec:
  selector:
    app: wininbrowser-wa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
