version: "3.0"
services:
  wininbrowser_authentication_db:
    hostname: wininbrowser_authentication_db
    build:
      context: ./authentication/database
      dockerfile: Dockerfile
    container_name: wininbrowser_authentication_db
    ports:
      - 55000:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_clock_db:
    hostname: wininbrowser_clock_db
    build:
      context: ./clock/database
      dockerfile: Dockerfile
    container_name: wininbrowser_clock_db
    env_file:
      - ./clock/database/env.list
    ports:
      - 3306:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_calendar_db:
    hostname: wininbrowser_calendar_db
    build:
      context: ./Calendar/database
      dockerfile: Dockerfile
    container_name: wininbrowser_calendar_db
    ports:
      - 65001:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_authentication_ms:
    hostname: wininbrowser_authentication_ms
    build:
      context: ./authentication/logic
      dockerfile: Dockerfile
    container_name: wininbrowser_authentication_ms
    ports:
      - 8000:8000
    depends_on:
      - wininbrowser_authentication_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_clock_ms:
    hostname: wininbrowser_clock_ms
    build:
      context: ./clock/logic
      dockerfile: Dockerfile
    container_name: wininbrowser_clock_ms
    env_file:
      - ./clock/logic/env.list
    ports:
      - 9090:9090
    depends_on:
      - wininbrowser_clock_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_calendar_ms:
    hostname: wininbrowser_calendar_ms
    build:
      context: ./Calendar
      dockerfile: Dockerfile
    container_name: wininbrowser_calendar_ms
    ports:
      - 3000:3000
    depends_on:
      - wininbrowser_calendar_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_mq:
    hostname: wininbrowser_mq
    image: rabbitmq:3-alpine
    container_name: wininbrowser_mq
    ports:
      - 5672:5672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_ag:
    hostname: wininbrowser_ag
    build:
      context: ./wininbrowser_ag
      dockerfile: Dockerfile
    container_name: wininbrowser_ag
    ports:
      - 4000:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_int:
    hostname: wininbrowser_int
    build:
      context: ./wininbrowser_int
      dockerfile: Dockerfile
    container_name: wininbrowser_int
    ports:
      - 55694:55694
      - 29162:29162
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_wa:
    hostname: wininbrowser_wa
    build:
      context: ../wininbrowser_frontend
      dockerfile: Dockerfile
    container_name: wininbrowser_wa
    ports:
      - 8080:8080
    depends_on:
      - wininbrowser_ag
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - wininbrowser_ag:api
    restart: unless-stopped
  wininbrowser_int_rp:
    build:
      context: ./wininbrowser_int_rp
      dockerfile: Dockerfile
    container_name: wininbrowser_int_rp
    ports:
      - 55690:55690
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_ag_rp:
    build:
      context: ./wininbrowser_ag_rp
      dockerfile: Dockerfile
    container_name: wininbrowser_ag_rp
    ports:
      - 31695:31695
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_wa_rp:
    build:
      context: ./wininbrowser_wa_rp
      dockerfile: Dockerfile
    container_name: wininbrowser_wa_rp
    ports:
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  wininbrowser_ldap:
    image: osixia/openldap:1.1.8
    container_name: wininbrowser_ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "wininbrowser.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "wininbrowser.unal.edu.co"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: wininbrowser_ldap_client
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "wininbrowser_ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - wininbrowser_ldap