apiVersion: apps/v1
kind: Deployment
metadata:
  name: wininbrowser-wa-rp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wininbrowser-wa-rp
  template:
    metadata:
      labels:
        app: wininbrowser-wa-rp
    spec:
      containers:
        - name: wininbrowser-wa-rp
          image: judelgadoc/wininbrowser_wa_rp
          env:
           - name: UPSTREAM_SERVER
             value: 34.133.114.28
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: wininbrowser-wa-rp
spec:
  selector:
    app: wininbrowser-wa-rp
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
